"""create consultants table

Revision ID: a716a520a00a
Revises: 352b2bc8f04d
Create Date: 2026-01-02 00:47:07.033079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a716a520a00a'
down_revision: Union[str, None] = '352b2bc8f04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('office_name', sa.String(length=200), nullable=False),
    sa.Column('office_phone', sa.String(length=20), nullable=True),
    sa.Column('office_address', sa.String(length=300), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('specialties', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}', comment='배열: [visa, labor, contract, business]'),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), server_default='100000.00', nullable=False, comment='시간당 상담료 (원)'),
    sa.Column('total_reviews', sa.Integer(), server_default='0', nullable=True),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), server_default='0.00', nullable=True, comment='평균 평점 (0-5)'),
    sa.Column('availability', sa.Text(), nullable=True, comment='JSON: {"mon": "09:00-18:00", ...}'),
    sa.Column('max_consultations_per_day', sa.Integer(), server_default='5', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('average_rating >= 0 AND average_rating <= 5', name='check_average_rating'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_consultants_user_id')
    )
    op.create_index(op.f('ix_consultants_is_active'), 'consultants', ['is_active'], unique=False)
    op.create_index(op.f('ix_consultants_user_id'), 'consultants', ['user_id'], unique=True)
    # GIN 인덱스 (specialties 배열 검색용)
    op.create_index('idx_consultants_specialties', 'consultants', ['specialties'], unique=False, postgresql_using='gin')
    # 평점 내림차순 인덱스
    op.create_index('idx_consultants_average_rating', 'consultants', [sa.text('average_rating DESC')], unique=False)
    op.alter_column('users', 'visa_type',
               existing_type=sa.VARCHAR(length=100),
               comment='비자 유형: E-1, D-2, F-2 등',
               existing_nullable=True)
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               comment='선호 언어: ko, en',
               existing_nullable=True,
               existing_server_default=sa.text("'ko'::character varying"))
    op.alter_column('users', 'residential_area',
               existing_type=sa.VARCHAR(length=100),
               comment='거주 지역: 고양시 덕양구 등',
               existing_nullable=True)
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_nationality', table_name='users')
    op.drop_index('idx_users_residential_area', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_nationality'), 'users', ['nationality'], unique=False)
    op.create_index(op.f('ix_users_residential_area'), 'users', ['residential_area'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_residential_area'), table_name='users')
    op.drop_index(op.f('ix_users_nationality'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_residential_area', 'users', ['residential_area'], unique=False)
    op.create_index('idx_users_nationality', 'users', ['nationality'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'residential_area',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='거주 지역: 고양시 덕양구 등',
               existing_nullable=True)
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='선호 언어: ko, en',
               existing_nullable=True,
               existing_server_default=sa.text("'ko'::character varying"))
    op.alter_column('users', 'visa_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='비자 유형: E-1, D-2, F-2 등',
               existing_nullable=True)
    # 인덱스 삭제
    op.drop_index('idx_consultants_average_rating', table_name='consultants')
    op.drop_index('idx_consultants_specialties', table_name='consultants')
    op.drop_index(op.f('ix_consultants_user_id'), table_name='consultants')
    op.drop_index(op.f('ix_consultants_is_active'), table_name='consultants')
    op.drop_table('consultants')
    # ### end Alembic commands ###
