/**
 * 샘플 데이터 라이브러리
 * 개발/테스트용 UI 데모 데이터
 */

export const SAMPLE_JOBS = [
  {
    id: "1",
    position: "시설 관리 인력 (외국인)",
    company_name: "고양시청",
    location: "경기도 고양시 덕양구",
    employment_type: "contract",
    salary_range: "시급 15,000원 ~ 월 260만원",
    description: "공공시설(도서관, 체육시설, 문화시설 등)의 관리 업무를 수행합니다. 외국인 근로자 우대 모집.",
    deadline: "2026-02-28T23:59:59",
    created_at: "2026-01-03T10:00:00",
  },
  {
    id: "2",
    position: "도시 계획 연구원 (다문화 번역)",
    company_name: "서울특별시",
    location: "서울특별시 서대문구",
    employment_type: "full-time",
    salary_range: "월 280만원 ~ 350만원",
    description: "다문화 가정 및 외국인 정책에 대한 연구 및 다언어 번역 지원. 영어/중국어 능숙자 우대.",
    deadline: "2026-02-15T23:59:59",
    created_at: "2026-01-02T15:30:00",
  },
  {
    id: "3",
    position: "외국인 상담 지원사",
    company_name: "한국이주재단",
    location: "서울특별시 용산구",
    employment_type: "full-time",
    salary_range: "월 320만원",
    description: "외국인 근로자의 노동 관련 상담, 취업 알선, 고충 해결 지원. 다언어 능력 및 문화 이해 필요.",
    deadline: "2026-01-31T23:59:59",
    created_at: "2026-01-05T09:00:00",
  },
  {
    id: "4",
    position: "제조업 생산 현장 인력",
    company_name: "자동차 부품 제조사 A",
    location: "경기도 부천시",
    employment_type: "part-time",
    salary_range: "월 220만원",
    description: "자동차 부품 조립 및 검수 업무. 숙련자 교육 제공. 외국인 근로자 환영.",
    deadline: "2026-03-10T23:59:59",
    created_at: "2026-01-08T14:20:00",
  },
  {
    id: "5",
    position: "호텔 프론트 데스크 (다언어)",
    company_name: "호텔 B",
    location: "서울특별시 강남구",
    employment_type: "full-time",
    salary_range: "월 280만원 ~ 320만원",
    description: "외국인 고객 응대, 체크인/아웃, 프론트 서비스. 중국어/영어/일본어 능숙자 우대.",
    deadline: "2026-02-20T23:59:59",
    created_at: "2026-01-10T11:00:00",
  },
  {
    id: "6",
    position: "식음료 배달 및 물류 지원",
    company_name: "물류 센터 C",
    location: "경기도 파주시",
    employment_type: "part-time",
    salary_range: "월 210만원",
    description: "식음료 배송, 재고 관리, 물류 운영. 신체 건강한 자 우대. 면허 필요 없음.",
    deadline: "2026-01-25T23:59:59",
    created_at: "2026-01-12T08:30:00",
  },
];

export const SAMPLE_SUPPORTS = [
  {
    id: "1",
    title: "외국인 장려금 지원사업",
    category: "subsidy",
    description: "경기도에 거주하는 외국인 근로자에게 생활 안정을 위한 장려금을 지원합니다.",
    eligibility: "경기도에 거주하는 외국인 근로자로서, 아래 요건을 모두 충족해야 합니다.",
    eligible_visa_types: ["E-9", "H-2", "F-2", "F-6"],
    support_content: "월 최대 20만원 (월 임금 150만원 이하인 경우), 월 최대 10만원 (월 임금 150만원 초과인 경우)",
    department: "경기도 일자리경제국",
    department_phone: "031-8008-8313",
    department_website: "https://ggt.or.kr",
    application_period_start: "2026-01-01T00:00:00",
    application_period_end: "2026-12-31T23:59:59",
    official_link: "https://ggt.or.kr/foreigner/subsidy",
    status: "active",
    created_at: "2026-01-01T09:00:00",
  },
  {
    id: "2",
    title: "다문화 가정 아동 한국어 교육 지원",
    category: "education",
    description: "다문화 가정의 아동에게 무료 한국어 교육 프로그램을 제공합니다.",
    eligibility: "만 5세 ~ 18세 다문화 가정 아동으로서, 한국어 교육이 필요한 경우",
    eligible_visa_types: ["F-2", "F-6", "F-5"],
    support_content: "주 2회, 1회 90분 수업. 교재 무료 제공. 초급/중급/고급 반 운영.",
    department: "교육부",
    department_phone: "044-203-6900",
    department_website: "https://www.moe.go.kr",
    application_period_start: "2026-02-01T00:00:00",
    application_period_end: "2026-06-30T23:59:59",
    official_link: "https://www.multiculture.go.kr",
    status: "active",
    created_at: "2026-01-05T10:00:00",
  },
  {
    id: "3",
    title: "외국인 취업 성장 지원 사업",
    category: "training",
    description: "외국인 근로자의 한국어 능력 및 직무 스킬 향상을 위한 맞춤형 직무 훈련 프로그램.",
    eligibility: "경기도 내 외국인 근로자로서, 취업을 희망하고 6개월 이상 거주 중인 자",
    eligible_visa_types: ["E-9", "H-2", "F-2"],
    support_content: "직무별 맞춤형 훈련 (제조, 서비스, IT 등). 훈련비 전액 지원 + 교통비 지원.",
    department: "경기도 일자리경제국",
    department_phone: "031-8008-8314",
    department_website: "https://ggt.or.kr",
    application_period_start: "2026-01-15T00:00:00",
    application_period_end: "2026-03-31T23:59:59",
    official_link: "https://ggt.or.kr/training",
    status: "active",
    created_at: "2026-01-10T11:00:00",
  },
  {
    id: "4",
    title: "F-2 비자 체류 기간 연장 지원",
    category: "visa",
    description: "F-2 비자 소지자가 체류 기간 연장을 위한 법률 상담 및 문서 작성 지원.",
    eligibility: "F-2 비자 소지자로서 체류 기간 만료 3개월 이내인 자",
    eligible_visa_types: ["F-2"],
    support_content: "이민 변호사 무료 상담 (연 2회). 체류 연장 서류 작성 지원. 필요 시 법정 지원 연계.",
    department: "법무부",
    department_phone: "02-2110-3000",
    department_website: "https://www.moleg.go.kr",
    application_period_start: "2026-01-01T00:00:00",
    application_period_end: "2026-12-31T23:59:59",
    official_link: "https://www.moleg.go.kr",
    status: "active",
    created_at: "2026-01-03T13:00:00",
  },
  {
    id: "5",
    title: "새터민 청소년 입주자 임대 주택 지원",
    category: "housing",
    description: "거주지가 없는 새터민 청소년에게 임대 주택을 무료 제공합니다.",
    eligibility: "만 24세 미만 청소년으로서, 한국 거주 5년 미만이고 거주지가 없는 자",
    eligible_visa_types: ["H-2", "F-2", "F-6"],
    support_content: "월세 100% 지원 (최대 40만원). 최대 2년 거주 가능. 자립 생활 훈련 프로그램 병행.",
    department: "여성가족부",
    department_phone: "02-2100-6000",
    department_website: "https://www.mogef.go.kr",
    application_period_start: "2026-02-01T00:00:00",
    application_period_end: "2026-12-31T23:59:59",
    official_link: "https://www.mogef.go.kr",
    status: "active",
    created_at: "2026-01-08T14:00:00",
  },
];

export const SAMPLE_CONSULTATIONS = [
  {
    id: "1",
    consultation_type: "visa",
    consultation_method: "call",
    content: "F-2 비자 체류 기간 연장 절차에 대해 알고 싶습니다. 현재 체류 기간이 3개월 남았습니다.",
    amount: 50000,
    status: "matched",
    payment_status: "pending",
    consultant_id: "consultant-1",
    created_at: "2026-01-05T10:00:00",
  },
  {
    id: "2",
    consultation_type: "labor",
    consultation_method: "video",
    content: "고용계약서 작성 및 임금 체불 관련 법률 상담이 필요합니다.",
    amount: 30000,
    status: "scheduled",
    payment_status: "completed",
    consultant_id: "consultant-2",
    created_at: "2026-01-08T14:00:00",
  },
  {
    id: "3",
    consultation_type: "contract",
    consultation_method: "document",
    content: "임대차 계약서 내용 검토 및 수정 요청",
    amount: 40000,
    status: "completed",
    payment_status: "completed",
    consultant_id: "consultant-3",
    created_at: "2026-01-02T09:00:00",
  },
];



